"""Normalisation centralisée des verdicts de fact-checking.

Ce module transforme les verdicts hétérogènes produits par les organismes
de fact-checking vers les trois labels standards utilisés par CheckIt.AI :

- true : l'affirmation est considérée comme vraie ;
- false : l'affirmation est considérée comme fausse ou trompeuse ;
- not_classified : le verdict est absent, ambigu ou non convertible
  de manière fiable vers une classification binaire.

Le verdict brut et sa version normalisée sont conservés afin de garantir
la traçabilité des transformations.
"""

from __future__ import annotations

import re

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any
from unicodedata import combining, normalize

from src.article.processing.article_cleaner import clean_text

from src.logger import get_logger

logger = get_logger(__name__)

# Labels standards CheckIt.AI

FACT_CHECK_LABEL_TRUE = "true"
FACT_CHECK_LABEL_FALSE = "false"
FACT_CHECK_LABEL_NOT_CLASSIFIED = "not_classified"

FACT_CHECK_LABELS = {
    FACT_CHECK_LABEL_TRUE,
    FACT_CHECK_LABEL_FALSE,
    FACT_CHECK_LABEL_NOT_CLASSIFIED
}


# Motifs expliquant le résultat de la conversion

REASON_EXACT_MATCH = "exact_match"
REASON_TRUE_MARKER = "true_marker"
REASON_FALSE_MARKER = "false_marker"
REASON_AMBIGUOUS = "ambiguous"
REASON_EMPTY = "empty"
REASON_UNKNOWN = "unknown"


@dataclass(frozen=True, slots=True)
class FactCheckLabelResult:
    """Résultat détaillé de la conversion d'un verdict."""

    raw_value: str
    normalized_value: str
    label: str
    reason: str
    matched_value: str = ""

    @property
    def is_classified(self) -> bool:
        """Indique si le verdict a été converti en true ou false."""

        return self.label in {
            FACT_CHECK_LABEL_TRUE,
            FACT_CHECK_LABEL_FALSE
        }

    @property
    def is_true(self) -> bool:
        """Indique si le verdict est considéré comme vrai."""

        return self.label == FACT_CHECK_LABEL_TRUE

    @property
    def is_false(self) -> bool:
        """Indique si le verdict est considéré comme faux."""

        return self.label == FACT_CHECK_LABEL_FALSE

    def to_dict(self) -> dict[str, str | bool]:
        """Retourne le résultat sous une forme sérialisable."""

        return {
            "raw_value": self.raw_value,
            "normalized_value": self.normalized_value,
            "label": self.label,
            "reason": self.reason,
            "matched_value": self.matched_value,
            "is_classified": self.is_classified
        }


# Correspondances exactes considérées comme vraies

TRUE_EXACT_LABELS = {
    # Anglais
    "true",
    "correct",
    "accurate",
    "verified",
    "confirmed",
    "authentic",
    "genuine",
    "mostly true",
    "mostly correct",
    "largely true",
    "largely correct",
    "substantially correct",
    "supported",
    "well supported",
    "evidence supports this claim",
    "the claim is true",

    # Français
    "vrai",
    "vraie",
    "correct",
    "correcte",
    "exact",
    "exacte",
    "verifie",
    "verifiee",
    "confirme",
    "confirmee",
    "authentique",
    "plutot vrai",
    "plutot vraie",
    "plutot correct",
    "plutot correcte",
    "globalement vrai",
    "globalement vraie",
    "en grande partie vrai",
    "en grande partie vraie",
    "l'affirmation est vraie",

    # Autres formulations fréquentes
    "verdadero",
    "cierto",
    "correcto",
    "mostly accurate"
}


# Correspondances exactes considérées comme fausses

FALSE_EXACT_LABELS = {
    # Anglais
    "false",
    "fake",
    "incorrect",
    "inaccurate",
    "misleading",
    "deceptive",
    "fabricated",
    "manipulated",
    "altered",
    "doctored",
    "hoax",
    "scam",
    "disinformation",
    "misinformation",
    "mostly false",
    "largely false",
    "partly false",
    "partially false",
    "incorrect attribution",
    "wrong attribution",
    "never said",
    "not true",
    "untrue",
    "pants on fire",
    "image generated by ai",
    "ai generated image",
    "ai generated",
    "synthetic image",
    "digitally altered",
    "the claim is false",

    # Français
    "faux",
    "fausse",
    "incorrect",
    "incorrecte",
    "inexact",
    "inexacte",
    "trompeur",
    "trompeuse",
    "mensonger",
    "mensongere",
    "fabrique",
    "fabriquee",
    "invente",
    "inventee",
    "manipule",
    "manipulee",
    "modifie",
    "modifiee",
    "intox",
    "desinformation",
    "plutot faux",
    "plutot fausse",
    "en grande partie faux",
    "en grande partie fausse",
    "partiellement faux",
    "partiellement fausse",
    "fausse attribution",
    "n'a jamais dit",
    "n'a pas dit",
    "image generee par ia",
    "genere par ia",
    "generee par ia",
    "l'affirmation est fausse",

    # Autres formulations fréquentes
    "falso",
    "incorrecto",
    "enganoso"
}


# Verdicts volontairement non convertis vers un label binaire

AMBIGUOUS_EXACT_LABELS = {
    # Anglais
    "mixed",
    "mixture",
    "half true",
    "partly true",
    "partially true",
    "somewhat true",
    "some truth",
    "needs context",
    "missing context",
    "context missing",
    "out of context",
    "not the whole story",
    "more complicated",
    "mostly satire",
    "satire",
    "opinion",
    "prediction",
    "unproven",
    "unverified",
    "unsupported",
    "uncertain",
    "unclear",
    "unknown",
    "undetermined",
    "inconclusive",
    "insufficient evidence",
    "no evidence",
    "no proof",
    "no rating",
    "not rated",
    "cannot be verified",
    "cannot verify",
    "unable to verify",
    "research in progress",
    "under investigation",
    "disputed",

    # Français
    "mitige",
    "mitigee",
    "partage",
    "partagee",
    "a nuancer",
    "nuance",
    "partiellement vrai",
    "partiellement vraie",
    "moitie vrai",
    "moitie vraie",
    "hors contexte",
    "contexte manquant",
    "manque de contexte",
    "c'est plus complique",
    "plus complique",
    "satire",
    "parodie",
    "opinion",
    "prediction",
    "non prouve",
    "non prouvee",
    "non verifie",
    "non verifiee",
    "incertain",
    "incertaine",
    "inconnu",
    "inconnue",
    "indetermine",
    "indeterminee",
    "non concluant",
    "non concluante",
    "preuves insuffisantes",
    "aucune preuve",
    "impossible a verifier",
    "en cours de verification",
    "conteste",
    "contestee"
}


# Expressions ambiguës testées avant les marqueurs true et false

AMBIGUOUS_MARKERS = (
    "not enough evidence",
    "insufficient evidence",
    "absence of evidence",
    "no evidence",
    "no proof",
    "cannot be verified",
    "cannot verify",
    "unable to verify",
    "not independently verified",
    "not yet verified",
    "needs more context",
    "needs context",
    "missing context",
    "context missing",
    "out of context",
    "not the whole story",
    "more complicated",
    "partly true",
    "partially true",
    "half true",
    "somewhat true",
    "some truth",
    "mixed",
    "mixture",
    "unproven",
    "unverified",
    "unsupported",
    "uncertain",
    "unclear",
    "inconclusive",
    "undetermined",
    "under investigation",
    "research in progress",
    "satire",
    "parody",
    "opinion",
    "prediction",
    "a nuancer",
    "manque de contexte",
    "contexte manquant",
    "hors contexte",
    "partiellement vrai",
    "partiellement vraie",
    "moitie vrai",
    "moitie vraie",
    "plus complique",
    "non prouve",
    "non prouvee",
    "non verifie",
    "non verifiee",
    "preuves insuffisantes",
    "aucune preuve",
    "impossible a verifier",
    "en cours de verification"
)


# Expressions négatives testées avant les expressions positives

FALSE_MARKERS = (
    "is not true",
    "isn't true",
    "was not true",
    "were not true",
    "not accurate",
    "not correct",
    "not authentic",
    "not genuine",
    "not real",
    "claim is false",
    "the claim is false",
    "mostly false",
    "largely false",
    "partly false",
    "partially false",
    "false attribution",
    "incorrect attribution",
    "wrong attribution",
    "never said",
    "did not say",
    "didn't say",
    "did not happen",
    "never happened",
    "misleading",
    "deceptive",
    "fabricated",
    "manipulated",
    "digitally altered",
    "doctored",
    "generated by ai",
    "ai generated",
    "synthetic image",
    "deepfake",
    "hoax",
    "scam",
    "disinformation",
    "misinformation",
    "fake",
    "false",
    "incorrect",
    "inaccurate",
    "untrue",
    "n'est pas vrai",
    "n'est pas vraie",
    "n'est pas exact",
    "n'est pas exacte",
    "n'est pas authentique",
    "l'affirmation est fausse",
    "plutot faux",
    "plutot fausse",
    "partiellement faux",
    "partiellement fausse",
    "en grande partie faux",
    "en grande partie fausse",
    "fausse attribution",
    "n'a jamais dit",
    "n'a pas dit",
    "ne s'est jamais produit",
    "trompeur",
    "trompeuse",
    "mensonger",
    "mensongere",
    "fabrique",
    "fabriquee",
    "invente",
    "inventee",
    "manipule",
    "manipulee",
    "genere par ia",
    "generee par ia",
    "image generee par ia",
    "desinformation",
    "intox",
    "faux",
    "fausse",
    "incorrect",
    "incorrecte",
    "inexact",
    "inexacte"
)


TRUE_MARKERS = (
    "claim is true",
    "the claim is true",
    "mostly true",
    "mostly correct",
    "largely true",
    "largely correct",
    "substantially correct",
    "evidence supports",
    "supported by evidence",
    "confirmed as true",
    "verified as true",
    "authentic image",
    "authentic video",
    "authentic document",
    "verified",
    "confirmed",
    "accurate",
    "authentic",
    "genuine",
    "correct",
    "true",
    "l'affirmation est vraie",
    "plutot vrai",
    "plutot vraie",
    "plutot correct",
    "plutot correcte",
    "globalement vrai",
    "globalement vraie",
    "en grande partie vrai",
    "en grande partie vraie",
    "confirme comme vrai",
    "confirmee comme vraie",
    "verifie",
    "verifiee",
    "confirme",
    "confirmee",
    "authentique",
    "exact",
    "exacte",
    "correct",
    "correcte",
    "vrai",
    "vraie"
)


# Expressions permettant de supprimer certains préfixes sans valeur sémantique

RATING_PREFIXES = (
    "rating",
    "verdict",
    "evaluation",
    "fact check",
    "fact-check",
    "factcheck",
    "conclusion",
    "result",
    "resultat",
    "classification",
    "assessment",
    "our rating",
    "notre verdict",
    "notre evaluation"
)


def normalize_fact_check_text(value: Any) -> str:
    """Normalise un verdict avant sa comparaison.

    La fonction retire notamment :

    - les accents ;
    - les différences de casse ;
    - les apostrophes typographiques ;
    - la ponctuation ;
    - les balises ou caractères décoratifs ;
    - les espaces multiples.
    """

    text = clean_text(value).lower()

    if not text:
        return ""

    text = (
        text.replace("’", "'")
        .replace("`", "'")
        .replace("“", '"')
        .replace("”", '"')
        .replace("–", "-")
        .replace("—", "-")
        .replace("−", "-")
        .replace("&", " and ")
    )

    # Retire les accents sans ajouter de dépendance externe.
    decomposed = normalize("NFKD", text)
    text = "".join(
        character
        for character in decomposed
        if not combining(character)
    )

    # Remplace la ponctuation par des espaces sans supprimer
    # les apostrophes utiles aux marqueurs comme "n'a jamais dit".
    text = re.sub(
        r"[\[\]{}()<>|/\\:;,.!?\"*_+=~#@-]",
        " ",
        text
    )

    text = re.sub(r"\s+", " ", text).strip(" -_'")

    return remove_rating_prefix(text)

def remove_rating_prefix(value: str) -> str:
    """Retire un éventuel préfixe comme 'Verdict :' ou 'Rating :'."""

    normalized_value = value.strip()

    for prefix in sorted(RATING_PREFIXES, key=len, reverse=True):
        normalized_prefix = normalize_prefix(prefix)

        if normalized_value == normalized_prefix:
            return ""

        if normalized_value.startswith(f"{normalized_prefix} "):
            return normalized_value[len(normalized_prefix):].strip(" -_")

    return normalized_value


def normalize_prefix(value: str) -> str:
    """Normalise simplement un préfixe déjà connu."""

    decomposed = normalize("NFKD", value.lower())

    return " ".join(
        "".join(
            character
            for character in decomposed
            if not combining(character)
        ).replace("-", " ").split()
    )


def contains_marker(value: str, marker: str) -> bool:
    """Recherche un marqueur en respectant les limites des mots.

    Cela évite par exemple de détecter `true` dans un mot plus long.
    """

    if not value or not marker:
        return False

    pattern = rf"(?<![\w]){re.escape(marker)}(?![\w])"
    return re.search(pattern, value) is not None


def find_first_marker(
    value: str,
    markers: Sequence[str]
) -> str:
    """Retourne le premier marqueur trouvé dans un verdict."""

    # Les marqueurs les plus longs sont contrôlés en premier pour éviter
    # qu'un terme général masque une formulation plus précise.
    for marker in sorted(markers, key=len, reverse=True):
        if contains_marker(value, marker):
            return marker

    return ""


def build_not_classified_result(
    raw_value: str,
    normalized_value: str,
    reason: str,
    matched_value: str = ""
) -> FactCheckLabelResult:
    """Construit un résultat non classifié."""

    return FactCheckLabelResult(
        raw_value=raw_value,
        normalized_value=normalized_value,
        label=FACT_CHECK_LABEL_NOT_CLASSIFIED,
        reason=reason,
        matched_value=matched_value
    )


def classify_fact_check_label(value: Any) -> FactCheckLabelResult:
    """Convertit un verdict de fact-checking vers un label CheckIt.AI.

    L'ordre des vérifications est volontairement strict :

    1. verdict vide ;
    2. correspondance exacte ambiguë ;
    3. correspondance exacte fausse ;
    4. correspondance exacte vraie ;
    5. détection d'une formulation ambiguë ;
    6. détection d'une formulation fausse ;
    7. détection d'une formulation vraie ;
    8. verdict inconnu.

    Les formulations négatives sont contrôlées avant les formulations
    positives afin que `not true` ne soit jamais classé comme `true`.
    """

    raw_value = clean_text(value)
    normalized_value = normalize_fact_check_text(raw_value)

    if not normalized_value:
        return build_not_classified_result(
            raw_value=raw_value,
            normalized_value="",
            reason=REASON_EMPTY
        )

    # Les verdicts ambigus ne doivent jamais être forcés vers true ou false.
    if normalized_value in AMBIGUOUS_EXACT_LABELS:
        
        logger.debug("Verdict AMBIGUOUS : %r", raw_value)
        
        return build_not_classified_result(
            raw_value=raw_value,
            normalized_value=normalized_value,
            reason=REASON_AMBIGUOUS,
            matched_value=normalized_value
        )

    if normalized_value in FALSE_EXACT_LABELS:
        
        logger.debug("Verdict EXACT FALSE : %r", raw_value)
         
        return FactCheckLabelResult(
            raw_value=raw_value,
            normalized_value=normalized_value,
            label=FACT_CHECK_LABEL_FALSE,
            reason=REASON_EXACT_MATCH,
            matched_value=normalized_value
        )

    if normalized_value in TRUE_EXACT_LABELS:
        
        logger.debug("Verdict EXACT TRUE : %r", raw_value)
        
        return FactCheckLabelResult(
            raw_value=raw_value,
            normalized_value=normalized_value,
            label=FACT_CHECK_LABEL_TRUE,
            reason=REASON_EXACT_MATCH,
            matched_value=normalized_value
        )

    ambiguous_marker = find_first_marker(
        normalized_value,
        AMBIGUOUS_MARKERS
    )

    if ambiguous_marker:
        return build_not_classified_result(
            raw_value=raw_value,
            normalized_value=normalized_value,
            reason=REASON_AMBIGUOUS,
            matched_value=ambiguous_marker
        )

    false_marker = find_first_marker(
        normalized_value,
        FALSE_MARKERS
    )
    
    if false_marker:
        return FactCheckLabelResult(
            raw_value=raw_value,
            normalized_value=normalized_value,
            label=FACT_CHECK_LABEL_FALSE,
            reason=REASON_FALSE_MARKER,
            matched_value=false_marker
        )

    true_marker = find_first_marker(
        normalized_value,
        TRUE_MARKERS
    )

    if true_marker:
        return FactCheckLabelResult(
            raw_value=raw_value,
            normalized_value=normalized_value,
            label=FACT_CHECK_LABEL_TRUE,
            reason=REASON_TRUE_MARKER,
            matched_value=true_marker
        )

    logger.debug(
        "Verdict inconnu | brut=%r | normalisé=%r",
        raw_value,
        normalized_value
    )

    return build_not_classified_result(
        raw_value=raw_value,
        normalized_value=normalized_value,
        reason=REASON_UNKNOWN
    )


def get_fact_check_label(value: Any) -> str:
    """Retourne uniquement le label true, false ou not_classified."""

    return classify_fact_check_label(value).label


def is_valid_fact_check_label(value: Any) -> bool:
    """Vérifie qu'une valeur est un label fact-checking standard."""

    normalized_value = normalize_fact_check_text(value).replace(
        " ",
        "_"
    )

    return normalized_value in FACT_CHECK_LABELS


def normalize_existing_fact_check_label(value: Any) -> str:
    """Normalise un label déjà présent dans un article.

    Cette fonction accepte notamment les anciennes valeurs `real` et `fake`
    afin de faciliter la transition vers les nouveaux labels.
    """

    normalized_value = normalize_fact_check_text(value)

    legacy_mapping = {
        "true": FACT_CHECK_LABEL_TRUE,
        "real": FACT_CHECK_LABEL_TRUE,
        "reel": FACT_CHECK_LABEL_TRUE,
        "vrai": FACT_CHECK_LABEL_TRUE,
        "1": FACT_CHECK_LABEL_TRUE,
        "false": FACT_CHECK_LABEL_FALSE,
        "fake": FACT_CHECK_LABEL_FALSE,
        "faux": FACT_CHECK_LABEL_FALSE,
        "0": FACT_CHECK_LABEL_FALSE,
        "not classified": FACT_CHECK_LABEL_NOT_CLASSIFIED,
        "not_classified": FACT_CHECK_LABEL_NOT_CLASSIFIED,
        "unknown": FACT_CHECK_LABEL_NOT_CLASSIFIED,
        "unclassified": FACT_CHECK_LABEL_NOT_CLASSIFIED,
        "non classe": FACT_CHECK_LABEL_NOT_CLASSIFIED,
        "non classee": FACT_CHECK_LABEL_NOT_CLASSIFIED,
        "": FACT_CHECK_LABEL_NOT_CLASSIFIED
    }

    return legacy_mapping.get(
        normalized_value,
        get_fact_check_label(value)
    )


def enrich_article_with_fact_check_label(
    article: Mapping[str, Any],
    raw_rating: Any,
    overwrite_label: bool = True
) -> dict[str, Any]:
    """Ajoute les informations de classification à un article.

    La fonction retourne une copie afin de ne pas modifier silencieusement
    l'objet reçu par l'appelant.
    """

    enriched_article = dict(article)
    result = classify_fact_check_label(raw_rating)

    if overwrite_label or not enriched_article.get("label"):
        enriched_article["label"] = result.label

    enriched_article["fact_check_rating"] = result.raw_value
    enriched_article["fact_check_rating_normalized"] = (
        result.normalized_value
    )
    enriched_article["fact_check_label_reason"] = result.reason
    enriched_article["fact_check_label_match"] = result.matched_value

    return enriched_article